#!/usr/bin/env bash
# install Nginx on the webserver

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown $USER:$USER /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
service nginx restart
