#!/usr/bin/env bash
# install Nginx on the webserver

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
service nginx restart
