#!/usr/bin/env bash
#installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" > haproxy
sudo mv haproxy /etc/default/haproxy


isBackEndSet=$( grep 'backend web-backend' < /etc/haproxy/haproxy.cfg )
if [ ! "$isBackEndSet" ]
then
block="\nbackend web-backend\n\tbalance roundrobin\n\t\
server 7765-web-01 34.239.169.253:80 check\n\tserver 7765-web-02 34.239.162.165:80 check"
echo -e "$block" >> /etc/haproxy/haproxy.cfg
fi

isFrontEndSet=$( grep 'frontend http' < /etc/haproxy/haproxy.cfg )
if [ ! "$isFrontEndSet" ]
then
block="\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"
echo -e "$block" >> /etc/haproxy/haproxy.cfg
fi

sudo service haproxy restart
