#!/usr/bin/env bash
#installing a load balancer

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 7765-web-01 34.239.169.253:80 check
    server 7765-web-02 34.239.162.165:80 check
    option httpchk" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
