#!/usr/bin/env bash
# A script to replace nginx configuration file with default settings
cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
service nginx restart
rm /run/nginx.pid
