#!/usr/bin/env bash
#A script that displays superstitious numbers
a=1
while ((a<=20))
do
	echo $a
	case $a in
	4)
		printf "bad luck from China\n";;
	9)
		printf "bad luck from Japan\n";;
	17)
		printf "bad luck from italy\n";;
	esac
	((a++))
	
done
