#!/usr/bin/env bash
#A script that displays the time for 12hours and 59 mminutes
hour=0
while ((hour<=12))
do
	echo "Hour: $hour"
	min=1
	while ((min<60))
	do
		echo $min
		((min++))
	done
	
	((hour++))
done
